"""Torna data_nascimento um campo obrigatório

Revision ID: 814a02305260
Revises: e62f2de1ecb0
Create Date: 2025-07-09 15:20:27.498225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814a02305260'
down_revision = 'e62f2de1ecb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
